# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-01 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import downloads.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jmbo', '0005_modelbase_layers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jmbo.ModelBase')),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to=b'downloads')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['primary_category', 'title'],
            },
            bases=('jmbo.modelbase',),
        ),
        migrations.CreateModel(
            name='TextOverlayTemporaryDownload',
            fields=[
                ('download_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='downloads.Download')),
                ('unique_per_user', models.BooleanField(default=False, editable=False)),
                ('background_image', models.ImageField(upload_to=b'downloads/mods')),
                ('text', models.TextField()),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('font', models.FilePathField(path=b'/usr/share/fonts/truetype/', recursive=True)),
                ('font_size', models.PositiveIntegerField()),
                ('colour', downloads.fields.ColourField()),
            ],
            options={
                'abstract': False,
            },
            bases=('downloads.download',),
        ),
    ]
